site_name: BIM Compendium
site_url: https://cadwork-bim.readthedocs.io/de/latest/
site_author: Michael Brunner
copyright: Copyright © 2021 - 2022 cadwork
theme:
  name: material
  logo: cw_logo.svg
  favicon: cw_logo.svg
  version: V29
  palette:
  - scheme: slate
    primary: "light-blue"
    accent: "pink"
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  - scheme: default
    primary: "light-blue"
    accent: "pink"
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - toc.integrate
    - navigation.tracking
    - navigation.tabs.sticky
markdown_extensions:
  - attr_list  
  - admonition
  - toc:
      permalink: false
  - meta
  - pymdownx.keys
  - footnotes:
      SEPARATOR: _footnote_
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets\extra.css


extra:
  social:
    - icon: fontawesome/brands/github
      # link: https://github.com/Brunner246
      name: BIM_Kompendium
  alternate:
    - name: Deutsch
      link: ./de/
      lang: de
    - name: Français
      link: ./fr/
      lang: fr
    - name: English
      link: ./en/
      lang: en
  analytics:
    provider: google
    property: G-MT51DC3GS2
plugins:
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT #  (set environment variable ENABLE_PDF_EXPORT to 1 to enable)

  - search:
      separator: '[\s\-\.\_]+'  
  - i18n:
      default_language: de
      languages:
        de: Deutsch
        fr: Français   
        en: English 
      nav_translations:
        fr:
          1_Import: 1.Import
          2_Modellierung: 2.Modélisation
          3_Export: 3.Export
          4_BCF: 4.BCF
          5_Beispiele: 5.Exemples
          6_Workflowsheets: 6.Workflowsheets
          7_Über: 7.À propos de nous
        en:
          1_Import: 1.Import
          2_Modellierung: 2.Modelling
          3_Export: 3.Export
          4_BCF: 4.BCF
          5_Beispiele: 5.Examples
          6_Workflowsheets: 6.Workflowsheets
          7_Über: 7.About
